Filtro de referee
AdriD-12/Proyecto_Moviles-P2024 pull request #18
Opened 2024-05-07 05:18 UTC by Gudynio

Se integro el filtro de referee y una pestaña de mapa para admin

2024-05-07 13:35 UTC, Darksw20 requested changes

2024-05-07 13:35 UTC, Darksw20 commented on lib/src/components/drawer_component.dart
> +                    'referee') // Mostrar solo si el usuario es "referee"
Referee no existe, los unicos valores validos son:
export enum USER_ROLES {
	ORGANIZER = "organizer",
	STAFF = "staff",
	USER = "user",
}

2024-05-07 20:36 UTC, Gudynio commented
Ya quedo

2024-05-08 03:20 UTC, Darksw20 approved these changes

2024-05-08 03:20 UTC, merged